# Generated by Django 3.0.5 on 2020-05-09 23:16

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import venueless.core.models.room
import venueless.core.models.world


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200430_2018"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room", options={"ordering": ("sorting_priority", "name")},
        ),
        migrations.AddField(
            model_name="user",
            name="moderation_state",
            field=models.CharField(
                choices=[("", "None"), ("silenced", "Silenced"), ("banned", "Banned")],
                default="",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="room",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel",
                to="core.Room",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="module_config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=venueless.core.models.room.empty_module_config, null=True
            ),
        ),
        migrations.AlterField(
            model_name="world",
            name="permission_config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=venueless.core.models.world.default_permissions,
                null=True,
            ),
        ),
    ]
