# Generated by Django 3.2.10 on 2021-12-27 00:06

from django.db import migrations
from django.utils.timezone import now


def add_permissions(apps, schema_editor):
    World = apps.get_model("core", "World")
    PlannedUsage = apps.get_model("core", "PlannedUsage")
    worlds = set(
        PlannedUsage.objects.all()
        .filter(end__gte=now())
        .values_list("world", flat=True)
    )
    for world in World.objects.filter(id__in=worlds):
        world.trait_grants["scheduleuser"] = ["schedule-update"]
        world.roles["scheduleuser"] = "world:api"
        world.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_poster_import_id"),
    ]

    operations = [
        migrations.RunPython(add_permissions, migrations.RunPython.noop),
    ]
