# Generated by Django 4.2.18 on 2025-01-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_world_vapid_private_key_world_vapid_public_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roulettepairing",
            name="room",
        ),
        migrations.RemoveField(
            model_name="roulettepairing",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="roulettepairing",
            name="user2",
        ),
        migrations.AlterUniqueTogether(
            name="rouletterequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rouletterequest",
            name="room",
        ),
        migrations.RemoveField(
            model_name="rouletterequest",
            name="user",
        ),
        migrations.DeleteModel(
            name="JanusServer",
        ),
        migrations.DeleteModel(
            name="RoulettePairing",
        ),
        migrations.DeleteModel(
            name="RouletteRequest",
        ),
    ]
