FROM python:3.11-bookworm

COPY pyproject.toml /pyproject.toml
RUN apt update && apt install -y poppler-utils && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip3 install -U pip wheel setuptools && pip3 install -Ue ".[dev]"
ENV VENUELESS_COMMIT_SHA=devcontainer
WORKDIR /app
EXPOSE 8375

