[project]
name = "venueless-server-local"
version = "0.0.0"
description = "Not for publishing - local development only"
requires-python = ">=3.12"
dependencies = [
    "aiofile==3.9.*",
    "aiohttp==3.13.2",
    "beautifulsoup4==4.13.*",
    "celery==5.5.*",
    "channels==4.3.*",
    "channels_redis==4.3.*",
    "daphne==4.2.*",
    "django-cors-headers==4.9.*",
    "django-decorator-include==3.3",
    "django-extensions==4.1",
    "django-formset-js-improved",
    "django-multifactor==0.8.3",
    "Django==4.2.*",
    "djangorestframework==3.16.*",
    "emoji==2.15.*",
    "gunicorn==23.0.0",
    "icalendar==6.3.*",
    "lxml==6.0.*",
    "matplotlib==3.10.*",
    "mozilla-django-oidc==4.0.*",
    "numpy==2.0.*",
    "openpyxl~=3.1.5",
    "orjson==3.11.*",
    "pandas==2.3.*",
    "pdf2image==1.17.*",
    "pdfrw==0.4",
    "Pillow==12.0.*",
    "psycopg2-binary==2.9.10",
    "pyjwt==2.10.*",
    "python-dateutil==2.9.*",
    "pytz",
    "pywebpush==2.0.*",
    "redis==7.0.1",
    "reportlab==4.4.*",
    "requests==2.32.*",
    "sentry-sdk==1.30.*",
    "tqdm==4.67.*",
    "uvicorn[standard]==0.38.0",
    "websockets==15.*",
    "yappi==1.7.3",
]

[project.optional-dependencies]
dev = [
    "aioresponses==0.7.8",
    "black==24.1",
    "flake8==7.3.0",
    "isort==6.0.1",
    "pytest-asyncio==1.2.0",
    "pytest-cov==7.0.0",
    "pytest-django==4.11.1",
    "pytest-rerunfailures==16.1",
    "pytest==8.4.2",
]
