[project]
name = "venueless-server-local"
version = "0.0.0"
description = "Not for publishing - local development only"
requires-python = ">=3.14"

dependencies = [
    "aiofile==3.9.*",
    "aiohttp==3.13.5",
    "beautifulsoup4==4.14.*",
    "celery==5.6.*",
    "channels==4.3.*",
    "daphne==4.2.*",
    "channels_redis==4.3.*",
    "django-cors-headers==4.9.*",
    "django-decorator-include==3.3",
    "django-extensions==4.1",
    "django-formset-js-improved",
    "django-multifactor==0.8.7",
    "Django==5.2.*",
    "djangorestframework==3.17.*",
    "emoji==2.15.*",
    "gunicorn==26.0.0",
    "icalendar==7.1.*",
    "lxml==6.1.*",
    "matplotlib==3.10.*",
    "mozilla-django-oidc==5.0.*",
    "numpy==2.4.*",
    "openpyxl~=3.1.5",
    "orjson==3.11.*",
    "pandas==3.0.*",
    "pdf2image==1.17.*",
    "Pillow==12.2.*",
    "psycopg2-binary==2.9.12",
    "pyjwt==2.12.*",
    "python-dateutil==2.9.*",
    "pytz",
    "pywebpush==2.3.*",
    "redis==7.4.0",
    "reportlab==4.5.*",
    "requests==2.33.*",
    "sentry-sdk==2.59.*",
    "svglib==1.6.*",
    "tqdm==4.67.*",
    "uvicorn[standard]==0.47.0",
    "websockets==16.*",
    "yappi==1.7.6",
]

[project.optional-dependencies]
dev = [
    "aioresponses==0.7.8",
    "black",
    "flake8",
    "isort",
    "pytest-asyncio==1.3.0",
    "pytest-cov==7.1.0",
    "pytest-django==4.12.0",
    "pytest-rerunfailures==16.1",
    "pytest==9.0.3",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
