[project]
name = "venueless-server-local"
version = "0.0.0"
description = "Not for publishing - local development only"
requires-python = ">=3.14"

dependencies = [
    "aiofile==3.12.*",
    "aiohttp==3.14.3",
    "beautifulsoup4==4.15.*",
    "celery==5.6.*",
    "channels==4.3.*",
    "daphne==4.2.*",
    "channels_redis==4.3.*",
    "django-cors-headers==4.9.*",
    "django-decorator-include==3.5",
    "django-extensions==4.1",
    "django-formset-js-improved",
    "django-multifactor==0.9.3",
    "Django==5.2.*",
    "djangorestframework==3.17.*",
    "emoji==2.15.*",
    "gunicorn==26.0.0",
    "icalendar==7.2.*",
    "lxml==6.1.*",
    "matplotlib==3.11.*",
    "mozilla-django-oidc==5.0.*",
    "numpy==2.5.*",
    "openpyxl~=3.1.5",
    "orjson==3.11.*",
    "pandas==3.0.*",
    "pdf2image==1.17.*",
    "Pillow==12.2.*",
    "psycopg2-binary==2.9.12",
    "pyjwt==2.13.*",
    "python-dateutil==2.9.*",
    "pytz",
    "pywebpush==2.3.*",
    "redis==8.1.0",
    "reportlab==5.0.*",
    "requests==2.34.*",
    "sentry-sdk==2.66.*",
    "svglib==2.1.*",
    "tqdm==4.70.*",
    "uvicorn[standard]==0.52.1",
    "websockets==17.*",
    "yappi==1.7.6",
]

[project.optional-dependencies]
dev = [
    "aioresponses==0.7.9",
    "black",
    "flake8",
    "isort",
    "pytest-asyncio==1.4.0",
    "pytest-cov==7.1.0",
    "pytest-django==4.12.0",
    "pytest-rerunfailures==16.4",
    "pytest==9.1.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []
