name: Server style
on:
  push:
    branches: [ dev, stable, prod ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ dev, stable, prod ]
    paths:
      - 'server/**'

jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.14
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python dependencies
        run: uv sync --extra dev
        working-directory: ./server
      - name: Minimize uv cache
        run: uv cache prune --ci
      - name: Run checks
        run: uv run black --check venueless tests
        working-directory: ./server
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python dependencies
        run: uv sync --extra dev
        working-directory: ./server
      - name: Minimize uv cache
        run: uv cache prune --ci
      - name: Run checks
        run: uv run flake8 venueless tests
        working-directory: ./server
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.14
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python dependencies
        run: uv sync --extra dev
        working-directory: ./server
      - name: Minimize uv cache
        run: uv cache prune --ci
      - name: Run checks
        run: uv run isort -c venueless tests
        working-directory: ./server
